config/routes.rb
Postit::Application.routes.draw do
  root :to => 'posts#index'
  resources :posts, :only => [:index, :show, :new, :create] do
    resources :comments, only: :create
  end
  resources :users, :only => [:show, :new, :create]
  resources :sessions, :only => [:create, :destroy]

  match '/posts/voteup/:id' => 'posts#voteup', :as => 'voteup_post'
  match '/posts/votedown/:id' => 'posts#votedown', :as => 'votedown_post'
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'login' => 'sessions#new', :as => 'login'
  get 'signup' => 'users#new', :as => 'signup'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	authenticates_with_sorcery!

  attr_accessible :comment, :post_id, :user_id

  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  authenticates_with_sorcery!

  attr_accessible :description, :url, :user_id, :voteup, :votedown, :votescore, :category
  validates :description, :presence => true
  validates :category, :presence => true

  belongs_to :user
  has_many :comments
  has_many :votes
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :name, :email, :password, 
									:password_confirmation, :username,
									:twitter

  has_many :posts
  has_many :comments
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :post_id, :user_id, :vote
  
  belongs_to :post
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def not_authenticated
  	redirect_to login_path, :alert => "First login to access this page."
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create!(params[:comment])
    flash[:notice] = "Thanks for commenting!"

    respond_to do |format|
      format.html { redirect_to post_path(@comment.post), notice: 'Comment was successfully created.' }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_login, :only => [:new, :create, :voteup, :votedown]

  def index
    @category = params[:category]

    if @category.nil?
      @posts = Post.all(order: "votescore DESC")
    else
      @posts = Post.find(
        :all,
        :conditions => "category = '#{@category}'")
    end
  end

  def show
    @post = Post.find(params[:id])
    @new_comment = @post.comments.build
  end

  def new
    @post = Post.new
    @post.user_id = current_user.id
  end

  def create
    @post = Post.new(params[:post])

    if @post.save
      redirect_to posts_path, notice: 'Post was successfully created.'
    else
      render action: "new", notice: 'Post failed to creat successfully.'
    end
  end

  def voteup
    @post = Post.find(params[:id])
    @vote = @post.votes.find(:all, :conditions => "user_id = #{current_user.id}")

    if @vote.empty?
      @post.votescore = @post.votescore + 1
      @post.save
      @vote = @post.votes.new(user_id: current_user.id)
      @vote.vote = "up"
      @vote.save

      respond_to do |format|
        format.html { redirect_to posts_url }
        format.js
      end
    else
      redirect_to posts_path, notice: 'You can only vote once'        
    end
  end

  def votedown
    @post = Post.find(params[:id])
    @vote = @post.votes.find(
      :all,
      :conditions => "user_id = #{current_user.id}")

    if @vote.empty?
      @post.votescore = @post.votescore - 1
      @post.save
      @vote = @post.votes.new(user_id: current_user.id)
      @vote.vote = "down"
      @vote.save

      respond_to do |format|
        format.html { redirect_to posts_url }
        format.js
      end
    else
      redirect_to posts_path, notice: 'You can only vote once'        
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = login(params[:username], params[:password])		

		if user
			redirect_back_or_to root_path, :notice => "Logged in!"
		else
			flash.now.alert = "Email or password was invalid"
			render :new
		end
	end

	def destroy
		logout
		redirect_to root_path :notice => "Logged out"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, only: :show

  def show
    @user = User.find(params[:id])
    @upvotecount = @user.votes.find(
      :all, 
      :conditions => "vote = 'up'").count
    @downvotecount = @user.votes.find(
      :all,
      :conditions => "vote = 'down'").count
    if @user.twitter.blank?
    else
      begin
        @twitterposts = Twitter.user_timeline(@user.twitter).first(20) if @user.twitter
      rescue
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      UserMailer.signup_confirmation(@user).deliver
      redirect_to posts_path, notice: 'User was successfully created.'
    else
      render action: "new"
    end
  end
end

app/views/comments/_comment.html.erb
<div class="comment">
  <div class="comment-body">
    <%= comment.comment %>
  </div>
  <% if comment.created_at != nil %>
  <div class="comment-details">    
    Posted <%= time_ago_in_words(comment.created_at)%> ago by <%= link_to "#{comment.user.name}", user_path(comment.user.id) %>
  </div>
  <% end %>
<div>

app/views/comments/create.js.erb
/* Insert a notice between the last commend and the new comment form */
$("#comment-notice").html('<div class="flash notice"><%= escape_javascript(flash.delete(:notice)) %></div>');

/* Add the new comment to the bottom of the comments list */
$("comments").append("<%= escape_javascript(render(@comment)) %>");

/* Highlight the new comment */
$("#comment_<%= @comment.id %>").effect("Highlight", {}, 3000);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Postit</title>
<%= stylesheet_link_tag "application", :media => "all" %>
javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"
javascript_include_tag "http://ajax.googleapis.com/ajax/jqueryui/1.7.2/jquery-ui.min.js"
javascript_include_tag "jquery-rails.js"

<%= csrf_meta_tags %>
</head>
	<body>
		<header class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<nav>
						<ul class="nav pull-left">
							<li><%= link_to "Home", posts_path %></li>
							<% if current_user %>
								<li><%= link_to current_user.username, user_path(current_user.id) %></li>
								<li><%= link_to "Log out", logout_path %></li>
							<% else %>
								<li><%= link_to "Sign up", signup_path %></li>
								<li><%= link_to "Log in", login_path %></li>
							<% end %>
						</ul>
					</nav>
				</div>
			</div>
		</header>
		
		<div class="container main-container">
			<%= yield %>
		</div>
	</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, rows: 4 %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="hidden_fields">
    <%= f.hidden_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="center">
	<p class="banner">
		<%= image_tag("pickle_jar.jpeg", alt: "Yup, a pickle jar", size: "50x50") %>
		<% if @category.nil? %>
			Pickle Juice
		<% else %>
			<%= @category.capitalize %>
		<% end %>
	</p>

	<%= link_to 'New Post', new_post_path, class: "btn new-post-link" %>
	
	<% @posts.each do |post| %>
	  <%= render 'shared/summary', post: post %>
	<% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
	<p id="notice"><%= notice %></p>

	<h3>Post:</h3>
	<%= render 'shared/summary', post: @post %>

	<div class="comments">
		<h3>Comments:</h3>
		<% @post.comments.each do |comment| %>
			<%= render 'comments/comment', comment: comment %>
		<% end %>

		<% if current_user %>
			<div class="add-comments">
				<h3>New Comment:</h3>
				<%= form_for [@post, @new_comment], :remote => true do |f| %>
						<%= f.label :comment %>
						<%= f.text_field :comment %>
				    <%= f.hidden_field :post_id, value: @post.id %><br />
				    <%= f.hidden_field :user_id, value: current_user.id %><br />
				    <%= f.submit "Add comment" %>
				<% end %>
			</div>
		<% end %>
	</div>

app/views/shared/_summary.erb
<table class="post-summary">
	<tr>
		<td class="post-score">
			<%= link_to "", voteup_post_path(post.id),
				remote: true,
				:class => 'icon-plus' %>
			<p id="post-score"><%= post.votescore %></p>
			<%= link_to "", votedown_post_path(post.id),
				remote: true,
				:class => 'icon-minus' %>
		</td>
		<td>
			<table class="post">
				<tr>
					<td class="url">
				  	<%= link_to post.description, post.url %>
				  </td>
				</tr>
				<tr>
					<td>
						  <h3>
						  	<%= link_to "Category: #{post.category}", posts_path(:category => post.category) %>
								<%= link_to "Poster: #{post.user.name}", user_path(post.user_id) %>
						    <%= link_to "Comments: #{post.comments.count}", post_path(post.id) %>
	  					</h3>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :twitter, 'Twitter Handle' %>
    <%= f.text_field :twitter %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Home', posts_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
	<b>Twitter Handle:</b>
	<%= @user.twitter %>
</p>

<h3>Posts:</h3>
<% @user.posts.each do |post| %>
	<%= render 'shared/summary', post: post %>
<% end %>

<h3>Comments:</h3>
<% if @user.comments.count == 0 %>
  No comments found
<% else %>
  <% @user.comments.each do |comment| %>
    <%= render 'comments/comment', comment: comment %>
  <% end %>
<% end %>

<h3>Votes:</h3>
Up Votes: <%= @upvotecount %><br />
Down Votes: <%= @downvotecount %>

<h3>Last 20 Twitter Posts</h3>
<% if @twitterposts %>
  <% @twitterposts.each do |tweet| %>
    <div class='tweet'>
      Created: <%= time_ago_in_words(tweet.created_at) %> ago<br />
      Tweet: <%= tweet.text %>
    </div>
  <% end %>
<% else %>
  No posts found
<% end %>